### ISSUE TITLE
[server] MySQL, 시퀄라이즈를 통한 DB 구현

### ISSUE THREAD

**Issue by hyuntae384** [codestates-beb/BEB-07-final-entasis#9]
데이터베이스 & ORM 구현
더미데이터 생성

**Comment by Russ481-k** [comment]
이슈 알람을 확인 합니다.

**Comment by hyuntae384** [comment]
1차적으로 데이터베이스 구현은 완료
현재는 아무 데이터가 없으며, 추후에 API를 구현하면서 스키마 수정이 발생할 수 있으며, 그 경우 이슈를 추가적으로 올리는 것으로 진행 예정
